# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-11-14 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='alarm_type',
            field=models.CharField(max_length=50, null=True, verbose_name='报警类型'),
        ),
        migrations.AlterField(
            model_name='test',
            name='ip',
            field=models.CharField(max_length=30, null=True, verbose_name='ip'),
        ),
        migrations.AlterField(
            model_name='test',
            name='source_time',
            field=models.DateTimeField(auto_now=True, verbose_name='报警时间'),
        ),
    ]
